/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    input s,
    input cout,
    output reg a,
    output reg b,
    output reg cin
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_fa_fsm_a;
  wire [1-1:0] M_fa_fsm_b;
  wire [1-1:0] M_fa_fsm_cin;
  wire [8-1:0] M_fa_fsm_statenow;
  reg [1-1:0] M_fa_fsm_s;
  reg [1-1:0] M_fa_fsm_cout;
  fa_fsm_2 fa_fsm (
    .clk(clk),
    .rst(rst),
    .s(M_fa_fsm_s),
    .cout(M_fa_fsm_cout),
    .a(M_fa_fsm_a),
    .b(M_fa_fsm_b),
    .cin(M_fa_fsm_cin),
    .statenow(M_fa_fsm_statenow)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = M_fa_fsm_statenow;
    io_led[0+7-:8] = {4'h8{M_fa_fsm_cin}};
    io_led[8+7-:8] = {4'h8{M_fa_fsm_b}};
    io_led[16+7-:8] = {4'h8{M_fa_fsm_a}};
    a = M_fa_fsm_a;
    b = M_fa_fsm_b;
    cin = M_fa_fsm_cin;
    M_fa_fsm_s = s;
    M_fa_fsm_cout = cout;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_seg = 8'hff;
    io_sel = 4'hf;
  end
endmodule
